//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 04:57:18 PM CEST 
//


package com.sun.java.xml.ns.javaee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 
 *                 
 *                 Defines the legal values for the <managed-bean-scope>
 *                 element's body content, which includes all of the scopes
 *                 normally used in a web application, plus the "none" value
 *                 indicating that a created bean should not be stored into
 *                 any scope.
 *                 
 * 
 *             
 * 
 * <p>Java class for faces-config-managed-bean-scopeOrNoneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faces-config-managed-bean-scopeOrNoneType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;http://java.sun.com/xml/ns/javaee>string">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faces-config-managed-bean-scopeOrNoneType", namespace = "http://java.sun.com/xml/ns/javaee")
public class FacesConfigManagedBeanScopeOrNoneType
    extends String
{


}
