//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.09 at 03:11:17 PM CEST 
//


package com.sun.java.xml.ns.javaee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 
 *                 The value of from-view-id must contain one of the following 
 *                 values:
 * 
 *                   - The exact match for a view identifier that is recognized
 *                     by the the ViewHandler implementation being used (such as
 *                     "/index.jsp" if you are using the default ViewHandler).
 * 
 *                   - A proper prefix of a view identifier, plus a trailing 
 *                     "*" character.  This pattern indicates that all view 
 *                     identifiers that match the portion of the pattern up to 
 *                     the asterisk will match the surrounding rule.  When more 
 *                     than one match exists, the match with the longest pattern 
 *                     is selected.
 * 
 *                   - An "*" character, which means that this pattern applies 
 *                     to all view identifiers.
 * 
 *             
 * 
 * <p>Java class for faces-config-from-view-idType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faces-config-from-view-idType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;http://java.sun.com/xml/ns/javaee>string">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faces-config-from-view-idType")
public class FacesConfigFromViewIdType
    extends String
{


}
