//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.09 at 03:11:17 PM CEST 
//


package com.sun.java.xml.ns.javaee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *                 Extension element for component.  It may contain 
 *                 implementation specific content.
 *             
 * 
 * <p>Java class for faces-config-component-extensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faces-config-component-extensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="base-component-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="component-family" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tag-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="designer-extension" type="{http://java.sun.com/xml/ns/javaee}designer-extension"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faces-config-component-extensionType", propOrder = {
    "baseComponentType",
    "componentFamily",
    "tagName",
    "designerExtension"
})
public class FacesConfigComponentExtensionType {

    @XmlElement(name = "base-component-type", required = true)
    protected java.lang.String baseComponentType;
    @XmlElement(name = "component-family", required = true)
    protected java.lang.String componentFamily;
    @XmlElement(name = "tag-name", required = true)
    protected java.lang.String tagName;
    @XmlElement(name = "designer-extension", required = true)
    protected DesignerExtension designerExtension;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the baseComponentType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getBaseComponentType() {
        return baseComponentType;
    }

    /**
     * Sets the value of the baseComponentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setBaseComponentType(java.lang.String value) {
        this.baseComponentType = value;
    }

    /**
     * Gets the value of the componentFamily property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getComponentFamily() {
        return componentFamily;
    }

    /**
     * Sets the value of the componentFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setComponentFamily(java.lang.String value) {
        this.componentFamily = value;
    }

    /**
     * Gets the value of the tagName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getTagName() {
        return tagName;
    }

    /**
     * Sets the value of the tagName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setTagName(java.lang.String value) {
        this.tagName = value;
    }

    /**
     * Gets the value of the designerExtension property.
     * 
     * @return
     *     possible object is
     *     {@link DesignerExtension }
     *     
     */
    public DesignerExtension getDesignerExtension() {
        return designerExtension;
    }

    /**
     * Sets the value of the designerExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesignerExtension }
     *     
     */
    public void setDesignerExtension(DesignerExtension value) {
        this.designerExtension = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
