//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 04:57:18 PM CEST 
//


package com.sun.java.xml.ns.javaee;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *                 
 *                 The "managed-bean" element represents a JavaBean, of a 
 *                 particular class, that will be dynamically instantiated 
 *                 at runtime (by the default VariableResolver implementation) 
 *                 if it is referenced as the first element of a value binding 
 *                 expression, and no corresponding bean can be identified in 
 *                 any scope.  In addition to the creation of the managed bean, 
 *                 and the optional storing of it into the specified scope, 
 *                 the nested managed-property elements can be used to 
 *                 initialize the contents of settable JavaBeans properties of 
 *                 the created instance.
 *                 
 *             
 * 
 * <p>Java class for faces-config-managed-beanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faces-config-managed-beanType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://java.sun.com/xml/ns/javaee}descriptionGroup"/>
 *         &lt;element name="managed-bean-name" type="{http://java.sun.com/xml/ns/javaee}java-identifierType"/>
 *         &lt;element name="managed-bean-class" type="{http://java.sun.com/xml/ns/javaee}fully-qualified-classType"/>
 *         &lt;element name="managed-bean-scope" type="{http://java.sun.com/xml/ns/javaee}faces-config-managed-bean-scopeOrNoneType"/>
 *         &lt;choice>
 *           &lt;element name="managed-property" type="{http://java.sun.com/xml/ns/javaee}faces-config-managed-propertyType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="map-entries" type="{http://java.sun.com/xml/ns/javaee}faces-config-map-entriesType"/>
 *           &lt;element name="list-entries" type="{http://java.sun.com/xml/ns/javaee}faces-config-list-entriesType"/>
 *         &lt;/choice>
 *         &lt;element name="managed-bean-extension" type="{http://java.sun.com/xml/ns/javaee}faces-config-managed-bean-extensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faces-config-managed-beanType", namespace = "http://java.sun.com/xml/ns/javaee", propOrder = {
    "description",
    "displayName",
    "icon",
    "managedBeanName",
    "managedBeanClass",
    "managedBeanScope",
    "managedProperty",
    "mapEntries",
    "listEntries",
    "managedBeanExtension"
})
public class FacesConfigManagedBeanType {

    protected List<DescriptionType> description;
    @XmlElement(name = "display-name")
    protected List<DisplayNameType> displayName;
    protected List<IconType> icon;
    @XmlElement(name = "managed-bean-name", required = true)
    protected JavaIdentifierType managedBeanName;
    @XmlElement(name = "managed-bean-class", required = true)
    protected FullyQualifiedClassType managedBeanClass;
    @XmlElement(name = "managed-bean-scope", required = true)
    protected FacesConfigManagedBeanScopeOrNoneType managedBeanScope;
    @XmlElement(name = "managed-property")
    protected List<FacesConfigManagedPropertyType> managedProperty;
    @XmlElement(name = "map-entries")
    protected FacesConfigMapEntriesType mapEntries;
    @XmlElement(name = "list-entries")
    protected FacesConfigListEntriesType listEntries;
    @XmlElement(name = "managed-bean-extension")
    protected List<FacesConfigManagedBeanExtensionType> managedBeanExtension;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisplayNameType }
     * 
     * 
     */
    public List<DisplayNameType> getDisplayName() {
        if (displayName == null) {
            displayName = new ArrayList<DisplayNameType>();
        }
        return this.displayName;
    }

    /**
     * Gets the value of the icon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IconType }
     * 
     * 
     */
    public List<IconType> getIcon() {
        if (icon == null) {
            icon = new ArrayList<IconType>();
        }
        return this.icon;
    }

    /**
     * Gets the value of the managedBeanName property.
     * 
     * @return
     *     possible object is
     *     {@link JavaIdentifierType }
     *     
     */
    public JavaIdentifierType getManagedBeanName() {
        return managedBeanName;
    }

    /**
     * Sets the value of the managedBeanName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JavaIdentifierType }
     *     
     */
    public void setManagedBeanName(JavaIdentifierType value) {
        this.managedBeanName = value;
    }

    /**
     * Gets the value of the managedBeanClass property.
     * 
     * @return
     *     possible object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public FullyQualifiedClassType getManagedBeanClass() {
        return managedBeanClass;
    }

    /**
     * Sets the value of the managedBeanClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public void setManagedBeanClass(FullyQualifiedClassType value) {
        this.managedBeanClass = value;
    }

    /**
     * Gets the value of the managedBeanScope property.
     * 
     * @return
     *     possible object is
     *     {@link FacesConfigManagedBeanScopeOrNoneType }
     *     
     */
    public FacesConfigManagedBeanScopeOrNoneType getManagedBeanScope() {
        return managedBeanScope;
    }

    /**
     * Sets the value of the managedBeanScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacesConfigManagedBeanScopeOrNoneType }
     *     
     */
    public void setManagedBeanScope(FacesConfigManagedBeanScopeOrNoneType value) {
        this.managedBeanScope = value;
    }

    /**
     * Gets the value of the managedProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the managedProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManagedProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FacesConfigManagedPropertyType }
     * 
     * 
     */
    public List<FacesConfigManagedPropertyType> getManagedProperty() {
        if (managedProperty == null) {
            managedProperty = new ArrayList<FacesConfigManagedPropertyType>();
        }
        return this.managedProperty;
    }

    /**
     * Gets the value of the mapEntries property.
     * 
     * @return
     *     possible object is
     *     {@link FacesConfigMapEntriesType }
     *     
     */
    public FacesConfigMapEntriesType getMapEntries() {
        return mapEntries;
    }

    /**
     * Sets the value of the mapEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacesConfigMapEntriesType }
     *     
     */
    public void setMapEntries(FacesConfigMapEntriesType value) {
        this.mapEntries = value;
    }

    /**
     * Gets the value of the listEntries property.
     * 
     * @return
     *     possible object is
     *     {@link FacesConfigListEntriesType }
     *     
     */
    public FacesConfigListEntriesType getListEntries() {
        return listEntries;
    }

    /**
     * Sets the value of the listEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacesConfigListEntriesType }
     *     
     */
    public void setListEntries(FacesConfigListEntriesType value) {
        this.listEntries = value;
    }

    /**
     * Gets the value of the managedBeanExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the managedBeanExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManagedBeanExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FacesConfigManagedBeanExtensionType }
     * 
     * 
     */
    public List<FacesConfigManagedBeanExtensionType> getManagedBeanExtension() {
        if (managedBeanExtension == null) {
            managedBeanExtension = new ArrayList<FacesConfigManagedBeanExtensionType>();
        }
        return this.managedBeanExtension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
