//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.09 at 03:11:17 PM CEST 
//


package com.sun.java.xml.ns.javaee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 
 *                 Extension element for property.  It may contain 
 *                 implementation specific content.
 * 
 *             
 * 
 * <p>Java class for faces-config-property-extensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faces-config-property-extensionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="default-value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="allow-run-time-binding" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="collection-property" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="property-item-class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="property-add-method" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="designer-extension" type="{http://java.sun.com/xml/ns/javaee}propertyDesignerExtensionType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faces-config-property-extensionType", propOrder = {
    "defaultValue",
    "allowRunTimeBinding",
    "collectionProperty",
    "propertyItemClass",
    "propertyAddMethod",
    "designerExtension"
})
public class FacesConfigPropertyExtensionType {

    @XmlElement(name = "default-value", required = true)
    protected java.lang.String defaultValue;
    @XmlElement(name = "allow-run-time-binding")
    protected Boolean allowRunTimeBinding;
    @XmlElement(name = "collection-property")
    protected Boolean collectionProperty;
    @XmlElement(name = "property-item-class", required = true)
    protected java.lang.String propertyItemClass;
    @XmlElement(name = "property-add-method", required = true)
    protected java.lang.String propertyAddMethod;
    @XmlElement(name = "designer-extension", required = true)
    protected PropertyDesignerExtensionType designerExtension;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the defaultValue property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDefaultValue(java.lang.String value) {
        this.defaultValue = value;
    }

    /**
     * Gets the value of the allowRunTimeBinding property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowRunTimeBinding() {
        return allowRunTimeBinding;
    }

    /**
     * Sets the value of the allowRunTimeBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowRunTimeBinding(Boolean value) {
        this.allowRunTimeBinding = value;
    }

    /**
     * Gets the value of the collectionProperty property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCollectionProperty() {
        return collectionProperty;
    }

    /**
     * Sets the value of the collectionProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCollectionProperty(Boolean value) {
        this.collectionProperty = value;
    }

    /**
     * Gets the value of the propertyItemClass property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPropertyItemClass() {
        return propertyItemClass;
    }

    /**
     * Sets the value of the propertyItemClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPropertyItemClass(java.lang.String value) {
        this.propertyItemClass = value;
    }

    /**
     * Gets the value of the propertyAddMethod property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPropertyAddMethod() {
        return propertyAddMethod;
    }

    /**
     * Sets the value of the propertyAddMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPropertyAddMethod(java.lang.String value) {
        this.propertyAddMethod = value;
    }

    /**
     * Gets the value of the designerExtension property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyDesignerExtensionType }
     *     
     */
    public PropertyDesignerExtensionType getDesignerExtension() {
        return designerExtension;
    }

    /**
     * Sets the value of the designerExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyDesignerExtensionType }
     *     
     */
    public void setDesignerExtension(PropertyDesignerExtensionType value) {
        this.designerExtension = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
