//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.09 at 03:11:17 PM CEST 
//


package com.sun.java.xml.ns.javaee;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sun.java.xml.ns.javaee package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FacesConfig_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "faces-config");
    private final static QName _FacesConfigFactoryTypeFacesContextFactory_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "faces-context-factory");
    private final static QName _FacesConfigFactoryTypeFactoryExtension_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "factory-extension");
    private final static QName _FacesConfigFactoryTypeApplicationFactory_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "application-factory");
    private final static QName _FacesConfigFactoryTypeRenderKitFactory_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "render-kit-factory");
    private final static QName _FacesConfigFactoryTypeLifecycleFactory_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "lifecycle-factory");
    private final static QName _FacesConfigApplicationTypeDefaultRenderKitId_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "default-render-kit-id");
    private final static QName _FacesConfigApplicationTypePropertyResolver_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "property-resolver");
    private final static QName _FacesConfigApplicationTypeResourceBundle_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "resource-bundle");
    private final static QName _FacesConfigApplicationTypeActionListener_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "action-listener");
    private final static QName _FacesConfigApplicationTypeLocaleConfig_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "locale-config");
    private final static QName _FacesConfigApplicationTypeElResolver_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "el-resolver");
    private final static QName _FacesConfigApplicationTypeApplicationExtension_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "application-extension");
    private final static QName _FacesConfigApplicationTypeNavigationHandler_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "navigation-handler");
    private final static QName _FacesConfigApplicationTypeViewHandler_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "view-handler");
    private final static QName _FacesConfigApplicationTypeStateManager_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "state-manager");
    private final static QName _FacesConfigApplicationTypeMessageBundle_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "message-bundle");
    private final static QName _FacesConfigApplicationTypeVariableResolver_QNAME = new QName("http://java.sun.com/xml/ns/javaee", "variable-resolver");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sun.java.xml.ns.javaee
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PropertyDesignerExtensionType }
     * 
     */
    public PropertyDesignerExtensionType createPropertyDesignerExtensionType() {
        return new PropertyDesignerExtensionType();
    }

    /**
     * Create an instance of {@link FacesConfigDefaultLocaleType }
     * 
     */
    public FacesConfigDefaultLocaleType createFacesConfigDefaultLocaleType() {
        return new FacesConfigDefaultLocaleType();
    }

    /**
     * Create an instance of {@link MessageDestinationRefType }
     * 
     */
    public MessageDestinationRefType createMessageDestinationRefType() {
        return new MessageDestinationRefType();
    }

    /**
     * Create an instance of {@link FacesConfigManagedBeanScopeOrNoneType }
     * 
     */
    public FacesConfigManagedBeanScopeOrNoneType createFacesConfigManagedBeanScopeOrNoneType() {
        return new FacesConfigManagedBeanScopeOrNoneType();
    }

    /**
     * Create an instance of {@link XsdQNameType }
     * 
     */
    public XsdQNameType createXsdQNameType() {
        return new XsdQNameType();
    }

    /**
     * Create an instance of {@link FacesConfigPropertyType }
     * 
     */
    public FacesConfigPropertyType createFacesConfigPropertyType() {
        return new FacesConfigPropertyType();
    }

    /**
     * Create an instance of {@link RunAsType }
     * 
     */
    public RunAsType createRunAsType() {
        return new RunAsType();
    }

    /**
     * Create an instance of {@link FacesConfigMapEntryType }
     * 
     */
    public FacesConfigMapEntryType createFacesConfigMapEntryType() {
        return new FacesConfigMapEntryType();
    }

    /**
     * Create an instance of {@link PersistenceContextRefType }
     * 
     */
    public PersistenceContextRefType createPersistenceContextRefType() {
        return new PersistenceContextRefType();
    }

    /**
     * Create an instance of {@link ResourceRefType }
     * 
     */
    public ResourceRefType createResourceRefType() {
        return new ResourceRefType();
    }

    /**
     * Create an instance of {@link ServiceRefHandlerChainsType }
     * 
     */
    public ServiceRefHandlerChainsType createServiceRefHandlerChainsType() {
        return new ServiceRefHandlerChainsType();
    }

    /**
     * Create an instance of {@link FacesConfigFacetType }
     * 
     */
    public FacesConfigFacetType createFacesConfigFacetType() {
        return new FacesConfigFacetType();
    }

    /**
     * Create an instance of {@link FacesConfigValueClassType }
     * 
     */
    public FacesConfigValueClassType createFacesConfigValueClassType() {
        return new FacesConfigValueClassType();
    }

    /**
     * Create an instance of {@link DesignerExtension }
     * 
     */
    public DesignerExtension createDesignerExtension() {
        return new DesignerExtension();
    }

    /**
     * Create an instance of {@link JndiNameType }
     * 
     */
    public JndiNameType createJndiNameType() {
        return new JndiNameType();
    }

    /**
     * Create an instance of {@link DisplayNameType }
     * 
     */
    public DisplayNameType createDisplayNameType() {
        return new DisplayNameType();
    }

    /**
     * Create an instance of {@link EnvEntryTypeValuesType }
     * 
     */
    public EnvEntryTypeValuesType createEnvEntryTypeValuesType() {
        return new EnvEntryTypeValuesType();
    }

    /**
     * Create an instance of {@link FacesConfigFacetExtensionType }
     * 
     */
    public FacesConfigFacetExtensionType createFacesConfigFacetExtensionType() {
        return new FacesConfigFacetExtensionType();
    }

    /**
     * Create an instance of {@link LocalHomeType }
     * 
     */
    public LocalHomeType createLocalHomeType() {
        return new LocalHomeType();
    }

    /**
     * Create an instance of {@link MessageDestinationLinkType }
     * 
     */
    public MessageDestinationLinkType createMessageDestinationLinkType() {
        return new MessageDestinationLinkType();
    }

    /**
     * Create an instance of {@link FacesConfigValidatorType }
     * 
     */
    public FacesConfigValidatorType createFacesConfigValidatorType() {
        return new FacesConfigValidatorType();
    }

    /**
     * Create an instance of {@link PersistenceUnitRefType }
     * 
     */
    public PersistenceUnitRefType createPersistenceUnitRefType() {
        return new PersistenceUnitRefType();
    }

    /**
     * Create an instance of {@link EjbRefType }
     * 
     */
    public EjbRefType createEjbRefType() {
        return new EjbRefType();
    }

    /**
     * Create an instance of {@link FacesConfigFactoryType }
     * 
     */
    public FacesConfigFactoryType createFacesConfigFactoryType() {
        return new FacesConfigFactoryType();
    }

    /**
     * Create an instance of {@link FacesConfigAttributeType }
     * 
     */
    public FacesConfigAttributeType createFacesConfigAttributeType() {
        return new FacesConfigAttributeType();
    }

    /**
     * Create an instance of {@link XsdBooleanType }
     * 
     */
    public XsdBooleanType createXsdBooleanType() {
        return new XsdBooleanType();
    }

    /**
     * Create an instance of {@link EmptyType }
     * 
     */
    public EmptyType createEmptyType() {
        return new EmptyType();
    }

    /**
     * Create an instance of {@link XsdAnyURIType }
     * 
     */
    public XsdAnyURIType createXsdAnyURIType() {
        return new XsdAnyURIType();
    }

    /**
     * Create an instance of {@link ResSharingScopeType }
     * 
     */
    public ResSharingScopeType createResSharingScopeType() {
        return new ResSharingScopeType();
    }

    /**
     * Create an instance of {@link HomeType }
     * 
     */
    public HomeType createHomeType() {
        return new HomeType();
    }

    /**
     * Create an instance of {@link PathType }
     * 
     */
    public PathType createPathType() {
        return new PathType();
    }

    /**
     * Create an instance of {@link FacesConfigApplicationType }
     * 
     */
    public FacesConfigApplicationType createFacesConfigApplicationType() {
        return new FacesConfigApplicationType();
    }

    /**
     * Create an instance of {@link FacesConfigConverterExtensionType }
     * 
     */
    public FacesConfigConverterExtensionType createFacesConfigConverterExtensionType() {
        return new FacesConfigConverterExtensionType();
    }

    /**
     * Create an instance of {@link ParamValueType }
     * 
     */
    public ParamValueType createParamValueType() {
        return new ParamValueType();
    }

    /**
     * Create an instance of {@link RoleNameType }
     * 
     */
    public RoleNameType createRoleNameType() {
        return new RoleNameType();
    }

    /**
     * Create an instance of {@link FacesConfigComponentExtensionType }
     * 
     */
    public FacesConfigComponentExtensionType createFacesConfigComponentExtensionType() {
        return new FacesConfigComponentExtensionType();
    }

    /**
     * Create an instance of {@link ResAuthType }
     * 
     */
    public ResAuthType createResAuthType() {
        return new ResAuthType();
    }

    /**
     * Create an instance of {@link EjbRefTypeType }
     * 
     */
    public EjbRefTypeType createEjbRefTypeType() {
        return new EjbRefTypeType();
    }

    /**
     * Create an instance of {@link GenericBooleanType }
     * 
     */
    public GenericBooleanType createGenericBooleanType() {
        return new GenericBooleanType();
    }

    /**
     * Create an instance of {@link MessageDestinationType }
     * 
     */
    public MessageDestinationType createMessageDestinationType() {
        return new MessageDestinationType();
    }

    /**
     * Create an instance of {@link FacesConfigMapEntriesType }
     * 
     */
    public FacesConfigMapEntriesType createFacesConfigMapEntriesType() {
        return new FacesConfigMapEntriesType();
    }

    /**
     * Create an instance of {@link TrueFalseType }
     * 
     */
    public TrueFalseType createTrueFalseType() {
        return new TrueFalseType();
    }

    /**
     * Create an instance of {@link FacesConfigApplicationExtensionType }
     * 
     */
    public FacesConfigApplicationExtensionType createFacesConfigApplicationExtensionType() {
        return new FacesConfigApplicationExtensionType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link ServiceRefType }
     * 
     */
    public ServiceRefType createServiceRefType() {
        return new ServiceRefType();
    }

    /**
     * Create an instance of {@link XsdIntegerType }
     * 
     */
    public XsdIntegerType createXsdIntegerType() {
        return new XsdIntegerType();
    }

    /**
     * Create an instance of {@link LifecycleCallbackType }
     * 
     */
    public LifecycleCallbackType createLifecycleCallbackType() {
        return new LifecycleCallbackType();
    }

    /**
     * Create an instance of {@link FacesConfigManagedBeanType }
     * 
     */
    public FacesConfigManagedBeanType createFacesConfigManagedBeanType() {
        return new FacesConfigManagedBeanType();
    }

    /**
     * Create an instance of {@link FacesConfigSupportedLocaleType }
     * 
     */
    public FacesConfigSupportedLocaleType createFacesConfigSupportedLocaleType() {
        return new FacesConfigSupportedLocaleType();
    }

    /**
     * Create an instance of {@link FacesConfigSuggestedValueType }
     * 
     */
    public FacesConfigSuggestedValueType createFacesConfigSuggestedValueType() {
        return new FacesConfigSuggestedValueType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link LocalType }
     * 
     */
    public LocalType createLocalType() {
        return new LocalType();
    }

    /**
     * Create an instance of {@link FacesConfigNavigationRuleExtensionType }
     * 
     */
    public FacesConfigNavigationRuleExtensionType createFacesConfigNavigationRuleExtensionType() {
        return new FacesConfigNavigationRuleExtensionType();
    }

    /**
     * Create an instance of {@link FacesConfigExtensionType }
     * 
     */
    public FacesConfigExtensionType createFacesConfigExtensionType() {
        return new FacesConfigExtensionType();
    }

    /**
     * Create an instance of {@link ServiceRefHandlerChainType }
     * 
     */
    public ServiceRefHandlerChainType createServiceRefHandlerChainType() {
        return new ServiceRefHandlerChainType();
    }

    /**
     * Create an instance of {@link FacesConfigNavigationRuleType }
     * 
     */
    public FacesConfigNavigationRuleType createFacesConfigNavigationRuleType() {
        return new FacesConfigNavigationRuleType();
    }

    /**
     * Create an instance of {@link FacesConfigRenderKitType }
     * 
     */
    public FacesConfigRenderKitType createFacesConfigRenderKitType() {
        return new FacesConfigRenderKitType();
    }

    /**
     * Create an instance of {@link FacesConfigLifecycleType }
     * 
     */
    public FacesConfigLifecycleType createFacesConfigLifecycleType() {
        return new FacesConfigLifecycleType();
    }

    /**
     * Create an instance of {@link FacesConfigConverterType }
     * 
     */
    public FacesConfigConverterType createFacesConfigConverterType() {
        return new FacesConfigConverterType();
    }

    /**
     * Create an instance of {@link FacesConfigFactoryExtensionType }
     * 
     */
    public FacesConfigFactoryExtensionType createFacesConfigFactoryExtensionType() {
        return new FacesConfigFactoryExtensionType();
    }

    /**
     * Create an instance of {@link FacesConfigNavigationCaseType }
     * 
     */
    public FacesConfigNavigationCaseType createFacesConfigNavigationCaseType() {
        return new FacesConfigNavigationCaseType();
    }

    /**
     * Create an instance of {@link FacesConfigApplicationResourceBundleType }
     * 
     */
    public FacesConfigApplicationResourceBundleType createFacesConfigApplicationResourceBundleType() {
        return new FacesConfigApplicationResourceBundleType();
    }

    /**
     * Create an instance of {@link FacesConfigRedirectType }
     * 
     */
    public FacesConfigRedirectType createFacesConfigRedirectType() {
        return new FacesConfigRedirectType();
    }

    /**
     * Create an instance of {@link XsdNonNegativeIntegerType }
     * 
     */
    public XsdNonNegativeIntegerType createXsdNonNegativeIntegerType() {
        return new XsdNonNegativeIntegerType();
    }

    /**
     * Create an instance of {@link XsdNMTOKENType }
     * 
     */
    public XsdNMTOKENType createXsdNMTOKENType() {
        return new XsdNMTOKENType();
    }

    /**
     * Create an instance of {@link SecurityRoleRefType }
     * 
     */
    public SecurityRoleRefType createSecurityRoleRefType() {
        return new SecurityRoleRefType();
    }

    /**
     * Create an instance of {@link EnvEntryType }
     * 
     */
    public EnvEntryType createEnvEntryType() {
        return new EnvEntryType();
    }

    /**
     * Create an instance of {@link FacesConfigRendererExtensionType }
     * 
     */
    public FacesConfigRendererExtensionType createFacesConfigRendererExtensionType() {
        return new FacesConfigRendererExtensionType();
    }

    /**
     * Create an instance of {@link FacesConfigReferencedBeanType }
     * 
     */
    public FacesConfigReferencedBeanType createFacesConfigReferencedBeanType() {
        return new FacesConfigReferencedBeanType();
    }

    /**
     * Create an instance of {@link FacesConfigAttributeExtensionType }
     * 
     */
    public FacesConfigAttributeExtensionType createFacesConfigAttributeExtensionType() {
        return new FacesConfigAttributeExtensionType();
    }

    /**
     * Create an instance of {@link FacesConfigManagedBeanExtensionType }
     * 
     */
    public FacesConfigManagedBeanExtensionType createFacesConfigManagedBeanExtensionType() {
        return new FacesConfigManagedBeanExtensionType();
    }

    /**
     * Create an instance of {@link IconType }
     * 
     */
    public IconType createIconType() {
        return new IconType();
    }

    /**
     * Create an instance of {@link FacesConfigFromViewIdType }
     * 
     */
    public FacesConfigFromViewIdType createFacesConfigFromViewIdType() {
        return new FacesConfigFromViewIdType();
    }

    /**
     * Create an instance of {@link EjbLocalRefType }
     * 
     */
    public EjbLocalRefType createEjbLocalRefType() {
        return new EjbLocalRefType();
    }

    /**
     * Create an instance of {@link FacesConfigManagedPropertyType }
     * 
     */
    public FacesConfigManagedPropertyType createFacesConfigManagedPropertyType() {
        return new FacesConfigManagedPropertyType();
    }

    /**
     * Create an instance of {@link FacesConfigLocaleConfigType }
     * 
     */
    public FacesConfigLocaleConfigType createFacesConfigLocaleConfigType() {
        return new FacesConfigLocaleConfigType();
    }

    /**
     * Create an instance of {@link FacesConfigValidatorExtensionType }
     * 
     */
    public FacesConfigValidatorExtensionType createFacesConfigValidatorExtensionType() {
        return new FacesConfigValidatorExtensionType();
    }

    /**
     * Create an instance of {@link FacesConfigLifecycleExtensionType }
     * 
     */
    public FacesConfigLifecycleExtensionType createFacesConfigLifecycleExtensionType() {
        return new FacesConfigLifecycleExtensionType();
    }

    /**
     * Create an instance of {@link FacesConfigComponentType }
     * 
     */
    public FacesConfigComponentType createFacesConfigComponentType() {
        return new FacesConfigComponentType();
    }

    /**
     * Create an instance of {@link ServiceRefHandlerType }
     * 
     */
    public ServiceRefHandlerType createServiceRefHandlerType() {
        return new ServiceRefHandlerType();
    }

    /**
     * Create an instance of {@link XsdStringType }
     * 
     */
    public XsdStringType createXsdStringType() {
        return new XsdStringType();
    }

    /**
     * Create an instance of {@link EjbLinkType }
     * 
     */
    public EjbLinkType createEjbLinkType() {
        return new EjbLinkType();
    }

    /**
     * Create an instance of {@link EjbRefNameType }
     * 
     */
    public EjbRefNameType createEjbRefNameType() {
        return new EjbRefNameType();
    }

    /**
     * Create an instance of {@link FacesConfigListEntriesType }
     * 
     */
    public FacesConfigListEntriesType createFacesConfigListEntriesType() {
        return new FacesConfigListEntriesType();
    }

    /**
     * Create an instance of {@link JavaIdentifierType }
     * 
     */
    public JavaIdentifierType createJavaIdentifierType() {
        return new JavaIdentifierType();
    }

    /**
     * Create an instance of {@link JavaTypeType }
     * 
     */
    public JavaTypeType createJavaTypeType() {
        return new JavaTypeType();
    }

    /**
     * Create an instance of {@link FacesConfigType }
     * 
     */
    public FacesConfigType createFacesConfigType() {
        return new FacesConfigType();
    }

    /**
     * Create an instance of {@link MessageDestinationTypeType }
     * 
     */
    public MessageDestinationTypeType createMessageDestinationTypeType() {
        return new MessageDestinationTypeType();
    }

    /**
     * Create an instance of {@link PortComponentRefType }
     * 
     */
    public PortComponentRefType createPortComponentRefType() {
        return new PortComponentRefType();
    }

    /**
     * Create an instance of {@link FacesConfigNullValueType }
     * 
     */
    public FacesConfigNullValueType createFacesConfigNullValueType() {
        return new FacesConfigNullValueType();
    }

    /**
     * Create an instance of {@link FacesConfigDefaultValueType }
     * 
     */
    public FacesConfigDefaultValueType createFacesConfigDefaultValueType() {
        return new FacesConfigDefaultValueType();
    }

    /**
     * Create an instance of {@link FacesConfigRendererType }
     * 
     */
    public FacesConfigRendererType createFacesConfigRendererType() {
        return new FacesConfigRendererType();
    }

    /**
     * Create an instance of {@link ListenerType }
     * 
     */
    public ListenerType createListenerType() {
        return new ListenerType();
    }

    /**
     * Create an instance of {@link MessageDestinationUsageType }
     * 
     */
    public MessageDestinationUsageType createMessageDestinationUsageType() {
        return new MessageDestinationUsageType();
    }

    /**
     * Create an instance of {@link FacesConfigRenderKitExtensionType }
     * 
     */
    public FacesConfigRenderKitExtensionType createFacesConfigRenderKitExtensionType() {
        return new FacesConfigRenderKitExtensionType();
    }

    /**
     * Create an instance of {@link FullyQualifiedClassType }
     * 
     */
    public FullyQualifiedClassType createFullyQualifiedClassType() {
        return new FullyQualifiedClassType();
    }

    /**
     * Create an instance of {@link XsdPositiveIntegerType }
     * 
     */
    public XsdPositiveIntegerType createXsdPositiveIntegerType() {
        return new XsdPositiveIntegerType();
    }

    /**
     * Create an instance of {@link UrlPatternType }
     * 
     */
    public UrlPatternType createUrlPatternType() {
        return new UrlPatternType();
    }

    /**
     * Create an instance of {@link RemoteType }
     * 
     */
    public RemoteType createRemoteType() {
        return new RemoteType();
    }

    /**
     * Create an instance of {@link FacesConfigPropertyExtensionType }
     * 
     */
    public FacesConfigPropertyExtensionType createFacesConfigPropertyExtensionType() {
        return new FacesConfigPropertyExtensionType();
    }

    /**
     * Create an instance of {@link InjectionTargetType }
     * 
     */
    public InjectionTargetType createInjectionTargetType() {
        return new InjectionTargetType();
    }

    /**
     * Create an instance of {@link ResourceEnvRefType }
     * 
     */
    public ResourceEnvRefType createResourceEnvRefType() {
        return new ResourceEnvRefType();
    }

    /**
     * Create an instance of {@link SecurityRoleType }
     * 
     */
    public SecurityRoleType createSecurityRoleType() {
        return new SecurityRoleType();
    }

    /**
     * Create an instance of {@link String }
     * 
     */
    public String createString() {
        return new String();
    }

    /**
     * Create an instance of {@link FacesConfigFromActionType }
     * 
     */
    public FacesConfigFromActionType createFacesConfigFromActionType() {
        return new FacesConfigFromActionType();
    }

    /**
     * Create an instance of {@link PersistenceContextTypeType }
     * 
     */
    public PersistenceContextTypeType createPersistenceContextTypeType() {
        return new PersistenceContextTypeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FacesConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "faces-config")
    public JAXBElement<FacesConfigType> createFacesConfig(FacesConfigType value) {
        return new JAXBElement<FacesConfigType>(_FacesConfig_QNAME, FacesConfigType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FullyQualifiedClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "faces-context-factory", scope = FacesConfigFactoryType.class)
    public JAXBElement<FullyQualifiedClassType> createFacesConfigFactoryTypeFacesContextFactory(FullyQualifiedClassType value) {
        return new JAXBElement<FullyQualifiedClassType>(_FacesConfigFactoryTypeFacesContextFactory_QNAME, FullyQualifiedClassType.class, FacesConfigFactoryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FacesConfigFactoryExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "factory-extension", scope = FacesConfigFactoryType.class)
    public JAXBElement<FacesConfigFactoryExtensionType> createFacesConfigFactoryTypeFactoryExtension(FacesConfigFactoryExtensionType value) {
        return new JAXBElement<FacesConfigFactoryExtensionType>(_FacesConfigFactoryTypeFactoryExtension_QNAME, FacesConfigFactoryExtensionType.class, FacesConfigFactoryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FullyQualifiedClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "application-factory", scope = FacesConfigFactoryType.class)
    public JAXBElement<FullyQualifiedClassType> createFacesConfigFactoryTypeApplicationFactory(FullyQualifiedClassType value) {
        return new JAXBElement<FullyQualifiedClassType>(_FacesConfigFactoryTypeApplicationFactory_QNAME, FullyQualifiedClassType.class, FacesConfigFactoryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FullyQualifiedClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "render-kit-factory", scope = FacesConfigFactoryType.class)
    public JAXBElement<FullyQualifiedClassType> createFacesConfigFactoryTypeRenderKitFactory(FullyQualifiedClassType value) {
        return new JAXBElement<FullyQualifiedClassType>(_FacesConfigFactoryTypeRenderKitFactory_QNAME, FullyQualifiedClassType.class, FacesConfigFactoryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FullyQualifiedClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "lifecycle-factory", scope = FacesConfigFactoryType.class)
    public JAXBElement<FullyQualifiedClassType> createFacesConfigFactoryTypeLifecycleFactory(FullyQualifiedClassType value) {
        return new JAXBElement<FullyQualifiedClassType>(_FacesConfigFactoryTypeLifecycleFactory_QNAME, FullyQualifiedClassType.class, FacesConfigFactoryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "default-render-kit-id", scope = FacesConfigApplicationType.class)
    public JAXBElement<String> createFacesConfigApplicationTypeDefaultRenderKitId(String value) {
        return new JAXBElement<String>(_FacesConfigApplicationTypeDefaultRenderKitId_QNAME, String.class, FacesConfigApplicationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FullyQualifiedClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "property-resolver", scope = FacesConfigApplicationType.class)
    public JAXBElement<FullyQualifiedClassType> createFacesConfigApplicationTypePropertyResolver(FullyQualifiedClassType value) {
        return new JAXBElement<FullyQualifiedClassType>(_FacesConfigApplicationTypePropertyResolver_QNAME, FullyQualifiedClassType.class, FacesConfigApplicationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FacesConfigApplicationResourceBundleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "resource-bundle", scope = FacesConfigApplicationType.class)
    public JAXBElement<FacesConfigApplicationResourceBundleType> createFacesConfigApplicationTypeResourceBundle(FacesConfigApplicationResourceBundleType value) {
        return new JAXBElement<FacesConfigApplicationResourceBundleType>(_FacesConfigApplicationTypeResourceBundle_QNAME, FacesConfigApplicationResourceBundleType.class, FacesConfigApplicationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FullyQualifiedClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "action-listener", scope = FacesConfigApplicationType.class)
    public JAXBElement<FullyQualifiedClassType> createFacesConfigApplicationTypeActionListener(FullyQualifiedClassType value) {
        return new JAXBElement<FullyQualifiedClassType>(_FacesConfigApplicationTypeActionListener_QNAME, FullyQualifiedClassType.class, FacesConfigApplicationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FacesConfigLocaleConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "locale-config", scope = FacesConfigApplicationType.class)
    public JAXBElement<FacesConfigLocaleConfigType> createFacesConfigApplicationTypeLocaleConfig(FacesConfigLocaleConfigType value) {
        return new JAXBElement<FacesConfigLocaleConfigType>(_FacesConfigApplicationTypeLocaleConfig_QNAME, FacesConfigLocaleConfigType.class, FacesConfigApplicationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FullyQualifiedClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "el-resolver", scope = FacesConfigApplicationType.class)
    public JAXBElement<FullyQualifiedClassType> createFacesConfigApplicationTypeElResolver(FullyQualifiedClassType value) {
        return new JAXBElement<FullyQualifiedClassType>(_FacesConfigApplicationTypeElResolver_QNAME, FullyQualifiedClassType.class, FacesConfigApplicationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FacesConfigApplicationExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "application-extension", scope = FacesConfigApplicationType.class)
    public JAXBElement<FacesConfigApplicationExtensionType> createFacesConfigApplicationTypeApplicationExtension(FacesConfigApplicationExtensionType value) {
        return new JAXBElement<FacesConfigApplicationExtensionType>(_FacesConfigApplicationTypeApplicationExtension_QNAME, FacesConfigApplicationExtensionType.class, FacesConfigApplicationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FullyQualifiedClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "navigation-handler", scope = FacesConfigApplicationType.class)
    public JAXBElement<FullyQualifiedClassType> createFacesConfigApplicationTypeNavigationHandler(FullyQualifiedClassType value) {
        return new JAXBElement<FullyQualifiedClassType>(_FacesConfigApplicationTypeNavigationHandler_QNAME, FullyQualifiedClassType.class, FacesConfigApplicationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FullyQualifiedClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "view-handler", scope = FacesConfigApplicationType.class)
    public JAXBElement<FullyQualifiedClassType> createFacesConfigApplicationTypeViewHandler(FullyQualifiedClassType value) {
        return new JAXBElement<FullyQualifiedClassType>(_FacesConfigApplicationTypeViewHandler_QNAME, FullyQualifiedClassType.class, FacesConfigApplicationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FullyQualifiedClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "state-manager", scope = FacesConfigApplicationType.class)
    public JAXBElement<FullyQualifiedClassType> createFacesConfigApplicationTypeStateManager(FullyQualifiedClassType value) {
        return new JAXBElement<FullyQualifiedClassType>(_FacesConfigApplicationTypeStateManager_QNAME, FullyQualifiedClassType.class, FacesConfigApplicationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "message-bundle", scope = FacesConfigApplicationType.class)
    public JAXBElement<String> createFacesConfigApplicationTypeMessageBundle(String value) {
        return new JAXBElement<String>(_FacesConfigApplicationTypeMessageBundle_QNAME, String.class, FacesConfigApplicationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FullyQualifiedClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/javaee", name = "variable-resolver", scope = FacesConfigApplicationType.class)
    public JAXBElement<FullyQualifiedClassType> createFacesConfigApplicationTypeVariableResolver(FullyQualifiedClassType value) {
        return new JAXBElement<FullyQualifiedClassType>(_FacesConfigApplicationTypeVariableResolver_QNAME, FullyQualifiedClassType.class, FacesConfigApplicationType.class, value);
    }

}
